name: Publish Docusaurus to staging

on:
  push:
    branches:
      - main
    paths:
      - 'docusaurus/**'

jobs:
  push_docusaurus:
    name: Publish docusaurus docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup Node 16
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 16
      - name: push
        uses: GetStream/push-stream-chat-docusaurus-action@main
        with:
          target-branch: 'production'
          destination-repository-name: 'stream-video-docusaurus'
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}
